
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/rtools45/x86_64-w64-mingw32.static.posix/share/cmake-3.31.8/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 6.2.9200 - AMD64
...
