name: quarto-docs

on:
  push:
    branches: [main, dev, 'release/**']
  pull_request:
    branches: [main, dev, 'release/**']

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Documentation
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: website
