name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      - uses: r-lib/actions/setup-rtools@v2

      - name: Install Inno Setup
        run: choco install innosetup -y

      - name: Build App and Installer
        run: |
          R CMD INSTALL .
          Rscript -e 'RDesk::build_app(app_dir = "inst/apps/mtcars_dashboard", app_name = "CarsAnalyser", build_installer = TRUE, portable_r_method = "installer")'

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: RDesk ${{ github.ref_name }}
          generate_release_notes: true
          draft: true
          files: |
            dist/*.zip
            dist/*-setup.exe
